# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Yl_Msgid.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Yl_Msgid.proto',
  package='Msgid',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eYl_Msgid.proto\x12\x05Msgid*\xd9\x02\n\x0cYLProtoMsgId\x12\x0e\n\nMSGID_Test\x10\x00\x12\x17\n\x12MSGID_INIT_CONNECT\x10\xe9\x07\x12\x15\n\x10MSGID_KEEP_ALIVE\x10\xec\x07\x12\x19\n\x14MSGID_QT_COMMAND_SUB\x10\xb9\x17\x12\x1e\n\x19MSGID_COMMAND_GetBasicQot\x10\xbc\x17\x12!\n\x1cMSGID_COMMAND_GetSnapshotQot\x10\xbd\x17\x12\x1f\n\x1aMSGID_COMMAND_GetTimeShare\x10\xc0\x17\x12\x1f\n\x1aMSGID_COMMAND_GetOrderBook\x10\xc4\x17\x12$\n\x1fMSGID_QT_DATA_UpdateSnapshotQot\x10\xe5\x19\x12!\n\x1cMSGID_QT_DATA_UpdateBasicQot\x10\xe6\x19\x12 \n\x1bMSGID_DATA_UpdateOrderBookt\x10\xe7\x19\x62\x06proto3'
)

_YLPROTOMSGID = _descriptor.EnumDescriptor(
  name='YLProtoMsgId',
  full_name='Msgid.YLProtoMsgId',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MSGID_Test', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSGID_INIT_CONNECT', index=1, number=1001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSGID_KEEP_ALIVE', index=2, number=1004,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSGID_QT_COMMAND_SUB', index=3, number=3001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSGID_COMMAND_GetBasicQot', index=4, number=3004,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSGID_COMMAND_GetSnapshotQot', index=5, number=3005,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSGID_COMMAND_GetTimeShare', index=6, number=3008,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSGID_COMMAND_GetOrderBook', index=7, number=3012,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSGID_QT_DATA_UpdateSnapshotQot', index=8, number=3301,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSGID_QT_DATA_UpdateBasicQot', index=9, number=3302,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSGID_DATA_UpdateOrderBookt', index=10, number=3303,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=26,
  serialized_end=371,
)
_sym_db.RegisterEnumDescriptor(_YLPROTOMSGID)

YLProtoMsgId = enum_type_wrapper.EnumTypeWrapper(_YLPROTOMSGID)
MSGID_Test = 0
MSGID_INIT_CONNECT = 1001
MSGID_KEEP_ALIVE = 1004
MSGID_QT_COMMAND_SUB = 3001
MSGID_COMMAND_GetBasicQot = 3004
MSGID_COMMAND_GetSnapshotQot = 3005
MSGID_COMMAND_GetTimeShare = 3008
MSGID_COMMAND_GetOrderBook = 3012
MSGID_QT_DATA_UpdateSnapshotQot = 3301
MSGID_QT_DATA_UpdateBasicQot = 3302
MSGID_DATA_UpdateOrderBookt = 3303


DESCRIPTOR.enum_types_by_name['YLProtoMsgId'] = _YLPROTOMSGID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
